const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assets = path.resolve(__dirname, '../web_dist/assets');
const source = fs.readFileSync(path.join(assets, 'dashboardOperations-v1.js'), 'utf8');
const context = vm.createContext({});
vm.runInContext(source.replace(/export /g, ''), context);
const display = context.dashboardOperationsDisplay;
const complete = {active_requests:199,scope:'cluster',expected_instances:8,responding_instances:8,complete:true};
assert.equal(display(complete).value, '199');
assert.equal(display(complete).caption, '集群采样 · 8/8 实例');
assert.equal(display(complete).warning, '');
assert.equal(display({...complete,active_requests:0}).value, '0');
assert.equal(display({...complete,responding_instances:6,complete:false}).value, '≥ 199');
assert.match(display({...complete,responding_instances:6}).warning, /统计不完整/);
assert.match(display({active_requests:1}).caption, /仅当前实例/);
assert.match(display({...complete,scope:'instance',expected_instances:1,responding_instances:1}).caption, /当前实例采样/);
for(const active_requests of [null,-1,'100',NaN,Infinity]) assert.equal(display({active_requests}).value,'--');
assert.equal(display(null).value, '--');
const bundle = fs.readFileSync(path.join(assets,'Dashboard-DoNiNtvp.js'),'utf8');
assert(bundle.includes('...dashboardOperationsDisplay(l.value)'));
assert(bundle.includes('dashboardOperationsDisplay(s.operations).warning'));
assert(bundle.includes('caption:o.caption'));
console.log('PASS: full cluster counts, partial sample warning, legacy compatibility and zero/invalid counts');
